### ISSUE TITLE
filled validator

### ISSUE THREAD

**Issue by arsydb** [dracony/PHPixie-validate#4]
Filled validator is implemented with php empty() function. 

The following things are considered to be empty:

"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
$var; (a variable declared, but without a value)

So, for example if I have combination of filled and numeric validators, value 0 (zero) is considered as invalid.

**Comment by roman-tsiupa-sociomantic** [comment]
Good catch! I think I will turn it into:

!in_array($val, array('', NULL))

Sounds good?

**Comment by nxeed** [comment]
Самое то

**Comment by Rayne** [comment]
@roman-tsiupa-sociomantic I think your proposal is not sufficient.

Example:

```php
foreach(['', 0, 0.0, '0', null, false, []] as $val) var_dump(!in_array($val, ['', NULL]));
```

`$val` | Result
--- | ---
`''` | `false`
`0` | `false`
`0.0` | `false`
`'0'` | `true`
`null` | `false`
`false` | `false`
`array()` | `false`

To address only strings, you could use `is_string($val) && $val !== ''` instead. It's also easier to understand.

**Comment by dracony** [comment]
thanks, after some trials I came up with https://github.com/dracony/PHPixie-validate/blob/master/classes/PHPixie/Validate/Ruleset.php#L43 This seems to get the job done
